=== KillerOfPie/PieLicense/ContributorsSchema/contributors.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://lic.pastrymaker-studios.com"
           xmlns="https://lic.pastrymaker-studios.com"
           elementFormDefault="qualified">

  <xs:complexType name="contributor">
    <xs:complexContent>
      <xs:extension base="contributorType">
        <xs:sequence>
          <xs:element name="changes" type="changes" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="contributorType">
    <xs:complexContent>
      <xs:extension base="contributingEntity">
        <xs:choice>
          <xs:element name="Human">
            <xs:complexType>


            </xs:complexType>
          </xs:element>
          <xs:element name="Non-Human">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="generativePrompt" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="generativePromptURL" type="xs:anyURI" minOccurs="0"/>
                <xs:element name="detail" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:any minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
              <xs:attribute name="TypeExt" default="Standard">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Standard"/>
                    <xs:enumeration value="AI"/>
                    <xs:enumeration value="ChatGPT"/>
                    <xs:enumeration value="Copilot Assisted"/>
                    <xs:pattern value="[a-zA-Z0-9]*"/>
                    <xs:whiteSpace value="replace"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:attribute>
              <xs:attribute name="version" type="xs:string"/>
            </xs:complexType>
          </xs:element>
        </xs:choice>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="contributingEntity">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="contact">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="organization" maxOccurs="unbounded">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="name" type="xs:string"/>
                  <xs:element name="url" type="xs:anyURI"/>
                  <xs:any minOccurs="0" maxOccurs="unbounded"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:choice maxOccurs="unbounded">
              <xs:element name="email" type="xs:string" maxOccurs="unbounded"/>
              <xs:element name="url" type="xs:anyURI" maxOccurs="unbounded"/>
              <xs:element name="github" type="github" maxOccurs="unbounded"/>
              <xs:element name="contactMethod" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string"/>
                    <xs:any maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:choice>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="gitCommit">
    <xs:annotation>
      <xs:documentation>Details of a git commit used to track changes that were made. (Optional)</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="repository" type="xs:anyURI"/>
      <xs:element name="hash">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="([a-fA-F0-9]{8}){1,5}"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="description" type="xs:string" minOccurs="0"/>
      <xs:element name="reason" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="singleDate">
    <xs:annotation>
      <xs:documentation>A single date that changes were made on.</xs:documentation>
    </xs:annotation>
    <xs:sequence/>
    <xs:attribute name="date" type="xs:date"/>
  </xs:complexType>

  <xs:complexType name="dateRange">
    <xs:annotation>
      <xs:documentation>A range of dates that changes were made between.</xs:documentation>
    </xs:annotation>
    <xs:sequence/>
    <xs:attribute name="from" type="xs:date" use="required"/>
    <xs:attribute name="to" type="xs:date" use="required"/>
    <xs:attribute name="inclusive" type="xs:boolean" default="true"/>
  </xs:complexType>

  <xs:complexType name="changes">
    <xs:annotation>
      <xs:documentation>Details of changes made and time period they were made.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="change" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:choice>
              <xs:element name="on" type="singleDate"/>
              <xs:element name="between" type="dateRange"/>
            </xs:choice>
            <xs:element name="commit" type="gitCommit" minOccurs="0" maxOccurs="unbounded"/>
            <xs:any minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="githubProfile">
    <xs:restriction base="xs:string">
      <xs:pattern value="^(https?://)?(www[.])?github[.]com/[a-zA-Z0-9_]{1,25}$"/>
      <xs:whiteSpace value="collapse"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="github">
    <xs:sequence>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="user" type="githubProfile"/>
        <xs:element name="org" type="githubProfile"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="contributors">
    <xs:annotation>
      <xs:documentation>Contributors to the project.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="authors" fixed="">
          <xs:annotation>
            <xs:documentation>Main contributors to the project.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="author" type="contributor" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="contributors">
          <xs:annotation>
            <xs:documentation>Contributors to the project.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element name="contributor" type="contributor" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


</xs:schema>

=== KillerOfPie/PieLicense/contributors.xml
<?xml version="1.0" encoding="UTF-8" ?>
<contributors xmlns="https://lic.pastrymaker-studios.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="https://lic.pastrymaker-studios.com https://raw.githubusercontent.com/KillerOfPie/PieLicense/master/ContributorsSchema/contributors.xsd">
  <authors>
    <author>
      <name>KillerOfPie</name>
      <contact>
        <organization>
          <name>PastryMaker-Studios</name>
          <url>https://dev.pastrymaker-studios.com</url>
        </organization>
        <email>me@killerofpie.com</email>
      </contact>
      <Human/>

      <changes>
        <change>
          <between from="2023-12-14" to="2023-12-15"/>
        </change>
      </changes>
    </author>
  </authors>
  <contributors/>
</contributors>
